version: '3.8'

services:

  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: "${NODE_ENV}"
    env_file:
      - .env
    depends_on:
    - postgres
    volumes:
    - .:/usr/src/app
    ports:
    - ${APP_PORT}:${APP_PORT}
    restart: always

  postgres:
    container_name: postgres
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: always
    
